# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './lab03/ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
os.environ['QT_OPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.Encrypt.setGeometry(QtCore.QRect(90, 480, 75, 23))
        self.Encrypt.setObjectName("Encrypt")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 180, 61, 16))
        self.label.setObjectName("label")
        self.Information = QtWidgets.QLabel(self.centralwidget)
        self.Information.setGeometry(QtCore.QRect(420, 180, 61, 16))
        self.Information.setObjectName("Information")
        self.CipherText = QtWidgets.QLabel(self.centralwidget)
        self.CipherText.setGeometry(QtCore.QRect(50, 330, 61, 16))
        self.CipherText.setObjectName("CipherText")
        self.Signature = QtWidgets.QLabel(self.centralwidget)
        self.Signature.setGeometry(QtCore.QRect(420, 330, 61, 16))
        self.Signature.setObjectName("Signature")
        self.Decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.Decrypt.setGeometry(QtCore.QRect(210, 480, 75, 23))
        self.Decrypt.setObjectName("Decrypt")
        self.Sign = QtWidgets.QPushButton(self.centralwidget)
        self.Sign.setGeometry(QtCore.QRect(480, 480, 75, 23))
        self.Sign.setObjectName("Sign")
        self.Verify = QtWidgets.QPushButton(self.centralwidget)
        self.Verify.setGeometry(QtCore.QRect(600, 480, 75, 23))
        self.Verify.setObjectName("Verify")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(260, 60, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.GerenateKeys = QtWidgets.QPushButton(self.centralwidget)
        self.GerenateKeys.setGeometry(QtCore.QRect(510, 70, 91, 23))
        self.GerenateKeys.setObjectName("GerenateKeys")
        self.PlainText = QtWidgets.QTextBrowser(self.centralwidget)
        self.PlainText.setGeometry(QtCore.QRect(120, 160, 271, 91))
        self.PlainText.setObjectName("PlainText")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(500, 160, 271, 91))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(120, 300, 271, 91))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(500, 300, 271, 91))
        self.textBrowser_4.setObjectName("textBrowser_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.label.setText(_translate("MainWindow", "Plain Text:"))
        self.Information.setText(_translate("MainWindow", "Information:"))
        self.CipherText.setText(_translate("MainWindow", "Cipher Text:"))
        self.Signature.setText(_translate("MainWindow", "Signature:"))
        self.Decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.Sign.setText(_translate("MainWindow", "Sign"))
        self.Verify.setText(_translate("MainWindow", "Verify"))
        self.label_5.setText(_translate("MainWindow", "RSA CIPHER"))
        self.GerenateKeys.setText(_translate("MainWindow", "Gerenate Keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
